version: "3.8"
services:
  backend:
    image: "ggeorgeuk/springboot-react-fullstack:4.3.2023.14.18.38"
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
    restart: "always"
