server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:postgresql://localhost:5432/in7min_db
spring.datasource.username=in7min
spring.datasource.password=passin7min
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true